name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: |
        sh scripts/package
    - name: Upload
      uses: actions/upload-artifact@v1.0.0
      with:
        name: pack.zip
        path: build/pack.zip
